name: Code Standards
on:
  pull_request:
    branches:
      - master
jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 2.x
      - name: flake8 Lint
        uses: reviewdog/action-flake8@v3
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          filter_mode: file
          fail_on_error: true
          flake8_args: '--ignore E501,E722,F,C9,N8 --exclude Contents/Libraries/Shared'
